### ISSUE TITLE
Using as docker compose file

### ISSUE THREAD

**Issue by danielmarkavis** [bymatej/minecraft-server#4]
So I created this as a `docker-compose.yml` file, but for some reason when I add the volumes, the docker restarts constantly.

```
version: "3.3"
services:
  mcmyadmin:
    image: bymatej/minecraft-server
    container_name: mcmyadmin
    environment:
      PUID: 1000
      PGID: 100
      EULA: 1
      JAVA_MAJOR_VERSION: 8
      MINECRAFT_FLAVOR: Forge
      MINECRAFT_VERSION: 1.16.5
      MCMA_PASSWORD: <password>
      JAVA_MEMORY: 12000
      DIFFICULTY: hard
      #ALLOW_FLIGHT: "true"
    volumes:
      - /home/<user>/Docker/mcmyadmin/Minecraft:/McMyAdmin/Minecraft
    ports:
      - 8080:8080
      - 25565:25565
    stop_grace_period: 30s
    network_mode: bridge
    restart: unless-stopped
```

I did notice that Volumes:

```
VOLUME /McMyAdmin/
WORKDIR /McMyAdmin/
```

Is at the bottom of the `Dockerfile`, would you need to declare it at the top?
